In [2]:
import tensorflow as tf


In [3]:
print(tf.__version__)

2.19.0


In [4]:
print(tf.config.list_physical_devices('GPU'))

[]


In [7]:
a = tf.constant(5)
print(a)
v = tf.constant([1,2,3,4])
print(v)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [9]:
m = tf.constant([[1,2],[3,4]])
print(m)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [12]:
t3 = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(t3 ,end =" ")

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32) 

In [13]:
x = tf.constant([1, 2, 3], dtype=tf.float32)
print(x)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [20]:
a = tf.constant([10,20,30])
b = tf.constant([50,60,70])
print(a+b)
print(a*b)
print(a -b)
print(b-a)
print(a /b)
print(a**b)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)
tf.Tensor([ 500 1200 2100], shape=(3,), dtype=int32)
tf.Tensor([-40 -40 -40], shape=(3,), dtype=int32)
tf.Tensor([40 40 40], shape=(3,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [21]:
v1 = tf.constant([1, 2, 3], dtype=tf.float32)
v2 = tf.constant([4, 5, 6], dtype=tf.float32)

print("\nVector Addition:", v1 + v2)
print("Vector Subtraction:", v1 - v2)
print("Vector Element-wise Multiplication:", v1 * v2)
print("Vector Element-wise Division:", v1 / v2)
print("Vector Power:", tf.pow(v1, v2))



Vector Addition: tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
Vector Subtraction: tf.Tensor([-3. -3. -3.], shape=(3,), dtype=float32)
Vector Element-wise Multiplication: tf.Tensor([ 4. 10. 18.], shape=(3,), dtype=float32)
Vector Element-wise Division: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float32)
Vector Power: tf.Tensor([  1.  32. 729.], shape=(3,), dtype=float32)


In [22]:
m1 = tf.constant([[1, 2],
                  [3, 4]], dtype=tf.float32)

m2 = tf.constant([[5, 6],
                  [7, 8]], dtype=tf.float32)

print("\nMatrix Addition:\n", m1 + m2)
print("Matrix Subtraction:\n", m1 - m2)
print("Matrix Element-wise Multiplication:\n", m1 * m2)
print("Matrix Element-wise Division:\n", m1 / m2)
print("Matrix Power:\n", tf.pow(m1, m2))



Matrix Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Matrix Subtraction:
 tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
Matrix Element-wise Multiplication:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Matrix Element-wise Division:
 tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
Matrix Power:
 tf.Tensor(
[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]], shape=(2, 2), dtype=float32)


In [14]:
z = tf.zeros((2, 3))
print(z)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [15]:
o = tf.ones((3, 2))
print(o)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [16]:
f = tf.fill((2, 2), 9)
print(f)

tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


In [17]:
r = tf.range(1, 10, 2)
print(r)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [24]:
import numpy as np
np_array = np.array([[1,2,3],[4,5,6]])
tensor = tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
